// const red = "Rouge"
// const black = "Noir"
// const odd = "Impair"
// const even = "Pair"
// const lowerNumber = "Manque (1 - 18)"
// const higherNumber = "Passe (19 - 36)"
// const firstDozen = "Douzaines 1st 12"
// const secondDozen = "Douzaines 2nd 12"
// const thirdDozen = "Douzaines 3rd 12"
// const firstColumn = "Colonnes (1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34)"
// const secondColumn = "Colonnes (2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35)"
// const thirdColumn = "Colonnes (3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36)"


export const numbers = [
    {
        number: 1,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 2,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 3,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 4,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 5,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 6,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 7,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 8,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 9,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 10,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 11,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 12,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: true,
        secondDozen: false,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 13,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 14,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 15,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 16,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 17,
        color: 'Red',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 18,
        color: 'Black',
        lowerNumber: true,
        higherNumber: false,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 19,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 20,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 21,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 22,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 23,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 24,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: true,
        thirdDozen: false,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 25,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: true,
        even: false,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 26,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 27,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 28,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: false,
        even: true,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 29,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 30,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 31,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: true,
        even: false,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 32,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 33,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
    {
        number: 34,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: false,
        even: true,
        firstColumn: true,
        secondColumn: false,
        thirdColumn: false
    },
    {
        number: 35,
        color: 'Red',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: true,
        even: false,
        firstColumn: false,
        secondColumn: true,
        thirdColumn: false
    },
    {
        number: 36,
        color: 'Black',
        lowerNumber: false,
        higherNumber: true,
        firstDozen: false,
        secondDozen: false,
        thirdDozen: true,
        odd: false,
        even: true,
        firstColumn: false,
        secondColumn: false,
        thirdColumn: true
    },
]